# 00 — Data Loading

This notebook loads all data that's necessary for futures steps. From raw csv files and wrds queries, we obtain three different parquet files in the `data/raw/`folder. No preprocessing is done.

| Raw file | Parquet file |
|---|---|
| `Chen_Zimmerman_monthly.csv` | `Chen_Zimmerman_monthly.parquet` |
| `daily_crsp.csv` | `daily_crsp.parquet` |
| `wrds_fetch` | `vix_parquet` |

The details of the functions are in the `/src/data_loading.py`file

In [6]:
import sys, os
sys.path.insert(0, os.path.join('..'))

import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from scipy.stats import spearmanr
import config

from src.data_loading import *

pd.set_option('display.float_format', '{:.4f}'.format)

## Loading `daily_crsp.csv`

The `load_crsp_polars()` function filters the PERMNO that have null entries.

In [7]:
df_raw = load_crsp_polars()
df_raw.head(3)

Saved as .parquet file to /Users/leowunderli/Documents/EPFL/MA2/ML_finance/01_ML_project/notebooks/../data/raw/daily_crsp_raw.parquet

shape: (3, 4)
┌────────┬────────────┬───────────┬───────────┐
│ PERMNO ┆ date       ┆ ret       ┆ mkt_ret   │
│ ---    ┆ ---        ┆ ---       ┆ ---       │
│ i32    ┆ date       ┆ f64       ┆ f64       │
╞════════╪════════════╪═══════════╪═══════════╡
│ 10001  ┆ 2000-01-03 ┆ 0.007353  ┆ -0.009549 │
│ 10001  ┆ 2000-01-04 ┆ -0.014599 ┆ -0.038345 │
│ 10001  ┆ 2000-01-05 ┆ 0.014815  ┆ 0.001922  │
└────────┴────────────┴───────────┴───────────┘

## Loading `Chen_Zimmerman_monthly.csv`

The `load_cz_monthly()` function gets rid of the columns with less than a certain completion factor (here the default is 90%). It also drops the columns that have too high a correlation (default is 0.95).

In [8]:
cz_daily = load_cz_monthly()
cz_daily.head(3)

Saved as .parquet file to /Users/leowunderli/Documents/EPFL/MA2/ML_finance/01_ML_project/notebooks/../data/raw/Chen_Zimmerman_monthly_raw.parquet

,date,AbnormalAccruals,Accruals,AccrualsBM,Activism1,Activism2,AdExp,AgeIPO,AM,AnalystRevision,...,TotalAccruals,UpRecomm,VarCF,VolMkt,VolSD,VolumeTrend,XFIN,zerotrade,zerotradeAlt1,zerotradeAlt12
0,1926-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1926-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1926-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Loading VIX from `wrds`

In [9]:
df_vix = load_VIX()
df_vix.head(3)

Loading library list...
Done
Saved as .parquet file to /Users/leowunderli/Documents/EPFL/MA2/ML_finance/01_ML_project/notebooks/../data/raw/vix_raw.parquet

        date     vix
0 2000-01-03 24.2100
1 2000-01-04 27.0100
2 2000-01-05 26.4100